---
# 数据库信息配置
master : "\n"
  type : mysql  # 数据库类型，支持mysql、sqlite2、sqlite3
  host : 127.0.0.1  # 数据库地址
  username : autotest_ankio_n  # 数据库用户名
  password :  ZwB8KbtzbExbFaWi # 数据库密码
  port : 3306  # 数据库端口
  db : autotest_ankio_n  # 数据库库名
  charset : utf8 # 数据库编码
# 配置其他数据库，直接往下添加即可
sqlite_websocket : "\n"#websocket数据库，用于会话保持
  type : sqlite3  # 数据库类型，支持mysql、sqlite2、sqlite3
  host : /storage/sql/websocket.db  # 数据库地址
  username :   # 数据库用户名
  password :   # 数据库密码
  port :   # 数据库端口
  db :   # 数据库库名
  charset : utf-8 # 数据库编码